server:
  port: 8888

spring:
  application:
    name: xyzp-gateway

  config:
    import: "optional:nacos:"

  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: mycluster
        ephemeral: false
        username: nacos
        password: nacos
      config:
        enabled: false
        username: nacos
        password: nacos

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://localhost:8083"
              - "http://localhost:8888"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000

      routes:
        - id: webservice-route
          uri: lb://webservice
          predicates:
            - Path=/api/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
